// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UuurkYjLA9wr_u4RNWQK2NHC2iNt9v0',
    appId: '1:212608780584:web:7a0895fa861d2d0a32e81d',
    messagingSenderId: '212608780584',
    projectId: 'mosaify-b923c',
    authDomain: 'mosaify-b923c.firebaseapp.com',
    storageBucket: 'mosaify-b923c.firebasestorage.app',
    measurementId: 'G-ZG91QZYXH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmNJ2Qv06U7RmZdYHn0bNIWdxZCZH_I0',
    appId: '1:212608780584:android:7898d95f104dd21532e81d',
    messagingSenderId: '212608780584',
    projectId: 'mosaify-b923c',
    storageBucket: 'mosaify-b923c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bNFTfyM_3zBK1jol5_z-j-WaqP1Y2z8',
    appId: '1:212608780584:ios:0b4ebd1f3c3feadd32e81d',
    messagingSenderId: '212608780584',
    projectId: 'mosaify-b923c',
    storageBucket: 'mosaify-b923c.firebasestorage.app',
    iosBundleId: 'com.mosaiccreator.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bNFTfyM_3zBK1jol5_z-j-WaqP1Y2z8',
    appId: '1:212608780584:ios:cacd242c9cc381d632e81d',
    messagingSenderId: '212608780584',
    projectId: 'mosaify-b923c',
    storageBucket: 'mosaify-b923c.firebasestorage.app',
    iosBundleId: 'com.example.mosaicCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0UuurkYjLA9wr_u4RNWQK2NHC2iNt9v0',
    appId: '1:212608780584:web:f93e7da1bcae55ba32e81d',
    messagingSenderId: '212608780584',
    projectId: 'mosaify-b923c',
    authDomain: 'mosaify-b923c.firebaseapp.com',
    storageBucket: 'mosaify-b923c.firebasestorage.app',
    measurementId: 'G-3MHYEJSFB4',
  );
}