name: Build Flutter iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-15   # ✅ macOS 15 has Xcode 16 with iOS 18 SDK

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"   # or your required version

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Show Xcode & SDK versions (debug)
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Build iOS (no codesign)
        run: flutter build ios --debug --no-codesign

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-debug
          path: build/ios/iphoneos/Runner.app

