name: Build Flutter iOS (Device)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-15   

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Disable code signing for CI
        run: |
          cd ios
          sed -i '' 's/CODE_SIGNING_ALLOWED = YES/CODE_SIGNING_ALLOWED = NO/g' Runner.xcodeproj/project.pbxproj


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS for device (no codesign)
        run: |
          flutter build ios --debug --no-codesign --simulator
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Debug \
                     -destination 'generic/platform=iOS' \
                     -allowProvisioningUpdates \
                     build

      - name: Package unsigned IPA (optional)
        run: |
          mkdir Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          zip -r Runner-simulator.ipa Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: Runner-simulator.ipa
