name: Build Flutter iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          cache: true
      - name: Install Dependencies
        run: flutter pub get
          # - name: Run Tests
          #   run: flutter test
      - name: Select Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app || sudo xcode-select -s /Applications/Xcode_14.3.app || echo "Specified Xcode version not found, using default"
          xcodebuild -version
          swift --version
      - name: Clean Pods
        working-directory: ios
        run: |
          rm -rf Pods
          rm Podfile.lock
      - name: Update Podfile with Specific Firebase Version
        working-directory: ios
        run: |
          sed -i '' 's|pod "Firebase/Auth"|pod "Firebase/Auth", "~> 10.11.0"|' Podfile || echo "Firebase/Auth not found, adding manually"
          sed -i '' 's|pod "Firebase/Core"|pod "Firebase/Core", "~> 10.11.0"|' Podfile || echo "Firebase/Core not found, adding manually"
          cat Podfile
      - name: Install Pods
        working-directory: ios
        run: pod install
      - name: Build iOS App
        run: flutter build ios --debug --no-codesign
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/
          if-no-files-found: error
