name: Build Flutter iOS (Device)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-15   # ✅ macOS 15 has Xcode 16 with iOS 18 SDK

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS for device (no codesign)
        run: |
          flutter build ios --debug --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Debug \
                     -destination 'generic/platform=iOS' \
                     build

      - name: Upload iOS device build
        uses: actions/upload-artifact@v4
        with:
          name: ios-device-build
          path: build/ios/iphoneos/Runner.app
