name: Flutter CI

# Controls when the action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs
jobs:
  build-android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Sets up Java environment (required for Android builds)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Using Zulu distribution which supports Java 24
          java-version: '24'   # Specify Java version 24 as requested

      # Sets up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9' # Replace with your Flutter version if needed
          channel: 'stable'
          cache: true

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run tests (optional, if you have tests set up)
      - name: Run Tests
        run: flutter test

      # Build APK for Android
      - name: Build Android APK
        run: flutter build apk --debug

      # Upload the APK as an artifact (optional, for downloading after build)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk