name: Build Flutter Android (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # Flutter environment info
      - name: Flutter doctor
        run: flutter doctor -v

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Android APK
      - name: Build APK (Release)
        run: flutter build apk --release

      # Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
